---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Scopri le modifiche più recenti alle funzionalità e ai servizi dati inclusi nella distribuzione locale della NetApp Console. 
---
= Modifiche recenti nella distribuzione locale di NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti alle funzionalità e ai servizi dati inclusi nella distribuzione locale della NetApp Console.



[[10-august-2026]]
== 10 agosto 2026



[[netapp-console-local-deployment]]
=== NetApp Console distribuzione locale



==== Presentazione della distribuzione locale di NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Scopri la distribuzione locale di NetApp Console"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti generali al backup e al ripristino NetApp

* *Supporto per la distribuzione locale di NetApp Console*: questa versione di NetApp Backup and Recovery supporta la distribuzione locale di NetApp Console in stato di anteprima.
* *Conservazione dei dati relativi ai job per 90 giorni*: NetApp Backup and Recovery ora conserva le informazioni sui job nel Job Monitor per 90 giorni.




==== Miglioramenti ai carichi di lavoro VMware

In questa versione, VMware workloads introduce i seguenti miglioramenti:

* *Supporto per il ripristino in una posizione alternativa per le VM SAN*: ora puoi ripristinare i backup delle VM basate su SAN in una posizione alternativa.
* *Supporto per l'eliminazione di più backup*: Ora puoi eliminare più backup contemporaneamente.


Per dettagli sulla protezione dei carichi di lavoro VMware, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro VMware"].



==== Miglioramenti dei carichi di lavoro Kubernetes

In questa versione, Kubernetes workloads introduce i seguenti miglioramenti:

* *Anteprima del supporto per risorse isolate*: se esegui NetApp Backup and Recovery in una distribuzione locale di NetApp Console, puoi individuare, proteggere e ripristinare risorse Kubernetes isolate. Questa funzionalità è in anteprima per questa versione.


Per dettagli sulla protezione dei carichi di lavoro Kubernetes, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro Kubernetes"].



==== Miglioramenti dei carichi di lavoro di ONTAP Volumes

In questa versione, i carichi di lavoro ONTAP Volumes introducono i seguenti miglioramenti:

* *Dai priorità ai processi di ripristino rispetto ai backup*: Ora puoi dare priorità ai processi di ripristino rispetto ai processi di backup quando ripristini macchine virtuali o file.
* *Scopri i sistemi e i volumi ONTAP senza attivare NetApp Backup and Recovery*: Ora puoi scoprire sistemi e volumi senza attivare NetApp Backup and Recovery.


Per informazioni dettagliate sulla protezione dei carichi di lavoro di ONTAP Volumes, fare riferimento a  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Panoramica dei carichi di lavoro di Protect ONTAP Volumes"].



[[13-july-2026]]
== 13 luglio 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Supporto multi-bucket migliorato per tutti i carichi di lavoro

NetApp Backup and Recovery ora supporta la protezione dei carichi di lavoro all'interno di un sistema con un massimo di 100 bucket distribuiti su diversi provider cloud. Per supportare più di 6 bucket per sistema è necessario ONTAP 9.19.1 o versioni successive.

Per dettagli su NetApp Backup e ripristino, consulta  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Scopri NetApp Backup and Recovery"].



[[15-june-2026]]
== 15 giugno 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti dei carichi di lavoro Kubernetes

In questa versione, Kubernetes workloads introduce i seguenti miglioramenti:

* *Trident Protect 26.06*: Questa versione include Trident Protect 26.06.
* *Salta la creazione dell'applicazione durante il ripristino*: Ora puoi saltare la creazione automatica dell'oggetto risorsa personalizzato dell'applicazione durante le operazioni di ripristino. Questo riduce le voci non necessarie nell'inventario dell'applicazione.
* *Ripristino delle persistent volume claim delle VM*: durante il ripristino delle applicazioni basate su VM, ora puoi ripristinare singole persistent volume claim senza ripristinare l'intera virtual machine, rendendo il recupero più veloce quando dischi o volumi specifici sono interessati da corruzione o perdita di dati.
* *Miglioramenti al monitoraggio dei processi*: Il monitoraggio dei processi ora offre una maggiore visibilità sui processi di protezione di Kubernetes. Puoi visualizzare informazioni dettagliate sullo stato dei processi e dei sottoprocessi e vedere lo storage di destinazione utilizzato da ciascuno di essi.


Per dettagli sulla protezione dei carichi di lavoro Kubernetes, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro Kubernetes"].



[[08-june-2026]]
== 8 giugno 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti dei carichi di lavoro di ONTAP Volumes

In questa versione, i carichi di lavoro ONTAP Volumes introducono il seguente miglioramento:

*Supporto per cloud storage compatibile S3*: NetApp Backup e ripristino per i carichi di lavoro di Volumes ora supporta il backup su cloud storage compatibile S3.

Per informazioni dettagliate sulla protezione dei carichi di lavoro di ONTAP Volumes, fare riferimento a  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Panoramica dei carichi di lavoro di Protect ONTAP Volumes"].



==== Miglioramenti ai carichi di lavoro Hyper-V

In questa versione, Hyper-V workloads introduce i seguenti miglioramenti:

* *Miglioramenti al ripristino di file e cartelle su una macchina virtuale guest*: ora è possibile ripristinare file e cartelle da uno snapshot su storage primario o secondario su una macchina virtuale Windows guest. Questa funzionalità è ora supportata per CIFS e per le macchine virtuali SAN.
* *I gruppi di protezione ora utilizzano la pianificazione del fuso orario dell'host*: I gruppi di protezione ora utilizzano il fuso orario dell'host Hyper-V. I gruppi di protezione creati prima dell'introduzione della pianificazione del fuso orario dell'host continuano a utilizzare l'ora configurata in precedenza (in genere UTC). Per aggiornare questi gruppi di protezione in modo che utilizzino il fuso orario dell'host Hyper-V, devi ricreare le pianificazioni. Consulta  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protection-groups.html["Crea e gestisci gruppi di protezione per i carichi di lavoro Hyper-V"] per ulteriori informazioni.


Per informazioni dettagliate sulla protezione dei carichi di lavoro Hyper-V, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro Hyper-V"].



==== Miglioramenti ai carichi di lavoro VMware

In questa versione, VMware workloads introduce il seguente miglioramento:

* *I gruppi di protezione ora utilizzano la pianificazione del fuso orario dell'host*: I gruppi di protezione ora utilizzano il fuso orario del server VMware vCenter host. I gruppi di protezione creati prima dell'introduzione della pianificazione del fuso orario dell'host continuano a essere eseguiti nel fuso orario configurato in precedenza (in genere UTC). Per utilizzare il fuso orario di vCenter, devi ricreare le pianificazioni. Consulta  https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protection-groups.html["Crea e gestisci gruppi di protezione per i carichi di lavoro VMware"] per ulteriori informazioni.


Per dettagli sulla protezione dei carichi di lavoro VMware, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro VMware"].
