---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, backup and recovery, ontap clusters, alerts, identity and access management, iam, recovery, netapp console local deployment, console local, local' 
summary: Scopri le modifiche più recenti alle funzionalità e ai servizi dati inclusi nella distribuzione locale della NetApp Console. 
---
= Modifiche recenti nella distribuzione locale di NetApp Console
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Scopri le modifiche più recenti alle funzionalità e ai servizi dati inclusi nella distribuzione locale della NetApp Console.



[[16-september-2026]]
== 16 settembre 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti generali al backup e al ripristino NetApp

In questa versione, i carichi di lavoro KVM, Hyper-V e VMware introducono il seguente miglioramento:

*Selezione delle credenziali durante il rilevamento dell'host VM*: Quando registri un host KVM, Hyper-V o VMware, ora puoi utilizzare le credenziali che hai già aggiunto a NetApp Backup and Recovery.



==== Miglioramenti ai carichi di lavoro Hyper-V

In questa versione, Hyper-V workloads introduce il seguente miglioramento:

*Protezione estesa dei dischi per le VM*: Per le configurazioni CIFS, NetApp Backup and Recovery ora supporta la protezione di ogni disco collegato a ciascuna VM in un gruppo di protezione. Questo include file distribuiti su più volumi ONTAP o sistemi di storage ONTAP (dischi estesi) e file limitati a una singola posizione.

Per informazioni dettagliate sulla protezione dei carichi di lavoro Hyper-V, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Scopri come proteggere i carichi di lavoro Hyper-V con NetApp Backup and Recovery"].



==== Miglioramento dei carichi di lavoro dei volumi ONTAP

In questa versione, i carichi di lavoro ONTAP Volumes introducono il seguente miglioramento in anteprima:

*Report giornaliero sul trasferimento dei dati di backup*: NetApp Backup and Recovery for Volumes ora include un report giornaliero sul trasferimento dei dati di backup nella scheda Report, che ti offre visibilità sull'attività giornaliera di trasferimento dei dati di backup e replica nell'intero ambiente. Puoi generare il report per l'intero account o per sistemi di storage selezionati, filtrare per intervallo di date e tipo di protezione e scaricare i risultati come CSV.

Per informazioni dettagliate sulla protezione dei carichi di lavoro di ONTAP Volumes, fare riferimento a  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Scopri la protezione dei volumi ONTAP con NetApp Backup and Recovery"].



[[17-august-2026]]
== 17 agosto 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti ai carichi di lavoro Hyper-V

In questa versione, Hyper-V workloads introduce il seguente miglioramento:

*Ripristina il backup dello storage a oggetti in una posizione alternativa*: Ora puoi ripristinare VM Hyper-V, file e cartelle dallo storage a oggetti in una posizione di archiviazione alternativa.

Per informazioni dettagliate sulla protezione dei carichi di lavoro Hyper-V, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-hyperv-protect-overview.html["Scopri come proteggere i carichi di lavoro Hyper-V con NetApp Backup and Recovery"].



==== Miglioramenti dei carichi di lavoro Kubernetes

In questa versione, Kubernetes workloads introduce i seguenti miglioramenti:

* *Trident Protect 26.08*: Questa versione include Trident Protect 26.08.
* *Tentativi di backup*: Ora puoi abilitare i tentativi di backup e configurare il numero di tentativi e gli intervalli tra di essi come impostazioni avanzate nelle policy di protezione di Kubernetes.
* *Backup parziale riuscito*: Ora puoi configurare le impostazioni avanzate nelle policy di protezione di Kubernetes per continuare il backup quando singole risorse falliscono, permettendo così ai processi di backup di completarsi come parzialmente riusciti. Questo ti consente di ripristinare le risorse sottoposte a backup anche se alcune risorse falliscono durante l'operazione di backup.
* *Backup crash-consistent e VM-consistent*: Il servizio Backup and Recovery per NetApp Console ora supporta la configurazione di criteri di protezione che creano backup o snapshot crash-consistent o VM-consistent. Puoi anche personalizzare come vengono eseguiti i freeze delle VM durante l'operazione di protezione.
* *Riconnetti il cluster Kubernetes in caso di modifica dell'indirizzo IP dell'agente Console*: Il servizio Backup and Recovery per NetApp Console ora ti permette di riconnettere un cluster al suo agente Console se l'indirizzo IP dell'agente cambia.
* *Migra il cluster al nuovo agente Console*: Il servizio Backup and Recovery per NetApp Console ora ti permette di migrare un cluster a un nuovo agente Console se l'agente originale si guasta o viene eliminato, garantendo una protezione continua delle app.


Per dettagli sulla protezione dei carichi di lavoro Kubernetes, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Scopri come proteggere i carichi di lavoro Kubernetes con NetApp Backup and Recovery"].



==== Miglioramento dei carichi di lavoro di Oracle Database

In questa versione, Oracle Database workloads introduce i seguenti miglioramenti:

* *Ripristino di pluggable database (PDB)*: Ora puoi ripristinare singoli pluggable database (PDB) e tablespace PDB, incluso il ripristino point-in-time.
* *Clonazione di Pluggable Database (PDB)*: ora puoi clonare un singolo PDB in un container database (CDB) esistente e, se vuoi, escludere i PDB quando cloni un intero container database.


Per informazioni dettagliate sulla protezione dei carichi di lavoro Oracle Database, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-oracle-protect-overview.html["Scopri come proteggere i carichi di lavoro di Oracle Database con NetApp Backup and Recovery"].



[[10-august-2026]]
== 10 agosto 2026



[[netapp-console-local-deployment]]
=== NetApp Console distribuzione locale



==== Presentazione della distribuzione locale di NetApp Console

https://docs.netapp.com/us-en/console-local/concept-netapp-console-local.html["Scopri la distribuzione locale di NetApp Console"].

https://docs.netapp.com/us-en/console-local/console-differences.html["Scopri le differenze tra la distribuzione locale di NetApp Console e NetApp Console SaaS e modalità privata"].



[[backup-and-recovery]]
=== Backup and Recovery



==== Miglioramenti generali al backup e al ripristino NetApp

* *Supporto per la distribuzione locale di NetApp Console*: questa versione di NetApp Backup and Recovery supporta la distribuzione locale di NetApp Console in stato di anteprima.
* *Conservazione dei dati relativi ai job per 90 giorni*: NetApp Backup and Recovery ora conserva le informazioni sui job nel Job Monitor per 90 giorni.




==== Miglioramenti ai carichi di lavoro VMware

In questa versione, VMware workloads introduce i seguenti miglioramenti:

* *Supporto per il ripristino in una posizione alternativa per le VM SAN*: ora puoi ripristinare i backup delle VM basate su SAN in una posizione alternativa.
* *Supporto per l'eliminazione di più backup*: Ora puoi eliminare più backup contemporaneamente.


Per dettagli sulla protezione dei carichi di lavoro VMware, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-vmware-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro VMware"].



==== Miglioramenti dei carichi di lavoro Kubernetes

In questa versione, Kubernetes workloads introduce i seguenti miglioramenti:

* *Anteprima del supporto per risorse isolate*: se esegui NetApp Backup and Recovery in una distribuzione locale di NetApp Console, puoi individuare, proteggere e ripristinare risorse Kubernetes isolate. Questa funzionalità è in anteprima per questa versione.


Per dettagli sulla protezione dei carichi di lavoro Kubernetes, fare riferimento a https://docs.netapp.com/us-en/data-services-backup-recovery/br-use-kubernetes-protect-overview.html["Panoramica sulla protezione dei carichi di lavoro Kubernetes"].



==== Miglioramenti dei carichi di lavoro di ONTAP Volumes

In questa versione, i carichi di lavoro ONTAP Volumes introducono i seguenti miglioramenti:

* *Dai priorità ai processi di ripristino rispetto ai backup*: Ora puoi dare priorità ai processi di ripristino rispetto ai processi di backup quando ripristini macchine virtuali o file.
* *Scopri i sistemi e i volumi ONTAP senza attivare NetApp Backup and Recovery*: Ora puoi scoprire sistemi e volumi senza attivare NetApp Backup and Recovery.


Per informazioni dettagliate sulla protezione dei carichi di lavoro di ONTAP Volumes, fare riferimento a  https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-protect-overview.html["Panoramica dei carichi di lavoro di Protect ONTAP Volumes"].



[[13-july-2026]]
== 13 luglio 2026



[[backup-and-recovery]]
=== Backup and Recovery



==== Supporto multi-bucket migliorato per tutti i carichi di lavoro

NetApp Backup and Recovery ora supporta la protezione dei carichi di lavoro all'interno di un sistema con un massimo di 100 bucket distribuiti su diversi provider cloud. Per supportare più di 6 bucket per sistema è necessario ONTAP 9.19.1 o versioni successive.

Per dettagli su NetApp Backup e ripristino, consulta  https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["Scopri NetApp Backup and Recovery"].
